services:
  caddy_first_proxy:
    image: caddy:latest
    container_name: caddy_first_proxy
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./caddy/first_proxy/Caddyfile:/etc/caddy/Caddyfile
      - ./certs/self-signed.crt:/etc/caddy/certs/self-signed.crt
      - ./certs/self-signed.key:/etc/caddy/certs/self-signed.key
    networks:
      - company-network
      - av-network

  caddy_second_proxy:
    image: caddy:latest
    container_name: caddy_second_proxy
    volumes:
      - ./caddy/second_proxy/Caddyfile:/etc/caddy/Caddyfile
      - ./certs/self-signed.crt:/etc/caddy/certs/self-signed.crt
      - ./certs/self-signed.key:/etc/caddy/certs/self-signed.key
    networks:
      - av-network

  caddy_fileserver:
    image: caddy:latest
    container_name: caddy_fileserver
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    volumes:
      - ./caddy/fileserver/Caddyfile:/etc/caddy/Caddyfile
      - ./static_files:/var/www/files
    ports:
      - "80:80"
    networks:
      - av-network

  master-talker:
    build: ./talker
    container_name: talker
    environment:
      - "ROS_HOSTNAME=talker"
      - "ROS_MASTER_URI=http://127.0.0.1:11311"
    command: |
      /bin/bash -c "roscore & source /opt/ros/noetic/setup.bash && sleep 10 && roslaunch rosbridge_server rosbridge_websocket.launch & sleep 10 && rostopic pub -r 2 /chatter std_msgs/String 'data: hello world'"
    networks:
      - av-network
    ports:
      - "9090:9090"

networks:
  company-network:
  av-network:
